# Generated by Django 5.0.7 on 2024-08-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_image_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/'),
        ),
    ]
