# Generated by Django 5.0.7 on 2024-08-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_home_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='home_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/'),
        ),
    ]
