# Generated by Django 5.0.7 on 2024-08-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_home_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
    ]
