# Generated by Django 5.0.7 on 2024-08-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_image_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
