# Generated by Django 5.0.7 on 2024-08-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_size_product_stock_qty_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
