# Generated by Django 5.0.7 on 2024-08-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_size_remove_product_size_remove_product_stock_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductSizeStock',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
