# Generated by Django 5.0.7 on 2024-08-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_size_remove_product_size_remove_product_stock_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.AddField(
            model_name='size',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
