# Generated by Django 5.0.7 on 2024-08-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_product_size_remove_product_stock_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
