# Generated by Django 5.0.7 on 2024-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_contact_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
