# Generated by Django 5.1 on 2024-09-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='product',
            field=models.CharField(default='', max_length=100),
        ),
    ]
