# Generated by Django 5.0.7 on 2024-08-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_invoice_order_paid'),
        ('store', '0025_contact_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariant'),
        ),
    ]
