# Generated by Django 5.1 on 2024-09-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_orderitems_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAIDORDER',
            fields=[
            ],
            options={
                'verbose_name': 'Paid Order',
                'verbose_name_plural': 'Paid Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.order',),
        ),
    ]
