# Generated by Django 5.1 on 2024-09-05 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paidorder'),
        ('store', '0027_alter_productvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.productvariant'),
        ),
    ]
